import { motion } from 'framer-motion';
import type { NextPage } from 'next';
import Head from 'next/head';
import Flow from '../src/components/Flow';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title></title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <motion.h1 layout className={styles.title}>
                    <b>El Ojo de Hubble</b>
                </motion.h1>

                <motion.div layout>
                    <Flow />
                </motion.div>
            </main>

            <footer className={styles.footer} style={{ textAlign: 'center' }}>
                Ezequiel Gimenez <br />
                Directores: Dr. Alejando Javier García, Lic. Federico Martín Schmidt
            </footer>
        </div>
    );
};

export default Home;
